[libdefaults]
    default_realm = KAFKA.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false

[realms]
    KAFKA.LOCAL = {
        kdc = kdc
        admin_server = kdc
    }

[domain_realm]
    .kafka.local = KAFKA.LOCAL
    kafka.local = KAFKA.LOCAL
    kafka1 = KAFKA.LOCAL
    kafka2 = KAFKA.LOCAL
    kafka3 = KAFKA.LOCAL
    kdc = KAFKA.LOCAL
