#!/bin/bash
###############################################################################
# configure.sh — Fill in host IP + passwords across all lab files
#
# Run this ONCE before quick-start.sh. It replaces every <PLACEHOLDER> in
# docker-compose.yml and scripts/*.sh with a real value: your host's IP
# (auto-detected, override-able) and randomly generated passwords.
#
# Generated values are saved to .env (gitignored) so you can find them again.
# Safe to re-run — it will refuse to run twice unless you pass --force,
# since a second run would break consistency with already-generated certs.
###############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
FORCE="${1:-}"

echo "=== Kafka Lab Configuration ==="
echo ""

if [ -f "$ENV_FILE" ] && [ "$FORCE" != "--force" ]; then
  echo "❌ $ENV_FILE already exists — configure.sh has already run."
  echo "   Re-running would desync already-generated certs/keytabs from new"
  echo "   passwords. If you really want to reconfigure from scratch:"
  echo "     rm -rf certs .env && docker compose down -v"
  echo "     ./scripts/configure.sh --force"
  exit 1
fi

# ─── 1. Detect host IP (override-able) ──────────────────────────────────────
DETECTED_IP="$(ip -4 addr show scope global 2>/dev/null | grep -oP 'inet \K[\d.]+' | head -1 || true)"
if [ -z "$DETECTED_IP" ]; then
  DETECTED_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
fi

echo "Detected host IP: ${DETECTED_IP:-<not found>}"
read -rp "Host IP to use for certs/listeners [${DETECTED_IP}]: " HOST_IP
HOST_IP="${HOST_IP:-$DETECTED_IP}"
if [ -z "$HOST_IP" ]; then
  echo "❌ No IP provided and none detected. Re-run and enter one manually."
  exit 1
fi

# ─── 2. Generate random passwords ───────────────────────────────────────────
gen_pass() { openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20; }

ADMIN_SCRAM_PASSWORD="$(gen_pass)"
APP_SCRAM_PASSWORD="$(gen_pass)"
DEMO_SCRAM_PASSWORD="$(gen_pass)"
SSL_KEYSTORE_PASSWORD="$(gen_pass)"
KDC_MASTER_PASSWORD="$(gen_pass)"

echo ""
echo "Generated random passwords for: admin, app-client, demo-user SCRAM users,"
echo "SSL keystores, and the Kerberos KDC. Saved to $ENV_FILE."

# ─── 3. Substitute placeholders into every file that uses them ─────────────
FILES=(
  "$REPO_ROOT/docker-compose.yml"
  "$SCRIPT_DIR/generate-certs.sh"
  "$SCRIPT_DIR/create-scram-users.sh"
  "$SCRIPT_DIR/setup-kerberos.sh"
  "$SCRIPT_DIR/../quick-start.sh"
)

for f in "${FILES[@]}"; do
  [ -f "$f" ] || continue
  sed -i \
    -e "s/<KAFKA_HOST_IP>/${HOST_IP}/g" \
    -e "s/<ADMIN_SCRAM_PASSWORD>/${ADMIN_SCRAM_PASSWORD}/g" \
    -e "s/<APP_SCRAM_PASSWORD>/${APP_SCRAM_PASSWORD}/g" \
    -e "s/<DEMO_SCRAM_PASSWORD>/${DEMO_SCRAM_PASSWORD}/g" \
    -e "s/<SSL_KEYSTORE_PASSWORD>/${SSL_KEYSTORE_PASSWORD}/g" \
    -e "s/<KDC_MASTER_PASSWORD>/${KDC_MASTER_PASSWORD}/g" \
    "$f"
done

# ─── 4. Save values for later reference (never committed — see .gitignore) ──
cat > "$ENV_FILE" <<EOF
# Generated by configure.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Keep this file private — it is excluded from git via .gitignore.
KAFKA_HOST_IP=${HOST_IP}
ADMIN_SCRAM_PASSWORD=${ADMIN_SCRAM_PASSWORD}
APP_SCRAM_PASSWORD=${APP_SCRAM_PASSWORD}
DEMO_SCRAM_PASSWORD=${DEMO_SCRAM_PASSWORD}
SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
KDC_MASTER_PASSWORD=${KDC_MASTER_PASSWORD}
EOF
chmod 600 "$ENV_FILE"

# ─── 5. Verify nothing was missed ───────────────────────────────────────────
REMAINING=$(grep -rl '<[A-Z_]*>' "$REPO_ROOT/docker-compose.yml" "$SCRIPT_DIR"/*.sh 2>/dev/null || true)
echo ""
if [ -n "$REMAINING" ]; then
  echo "⚠️  Some placeholders were not replaced — check these files:"
  echo "$REMAINING"
else
  echo "✅ All placeholders replaced. Values saved to .env."
fi
echo ""
echo "Next: ./quick-start.sh"
